### get all projects
GET http://localhost:5000/projects

### set student
POST http://localhost:5000/projects HTTP/1.1
content-type: application/json

{
  "name": "Ron Weasley",
  "city": "Tel Aviv",
  "description": "Some Description",
  "start_time": "2013-06-03 13:04:22.976182",
  "end_time": "2013-06-03 13:04:22.976182"
}